### ISSUE TITLE
Setup fails for NeoForge 26.3

### ISSUE THREAD

**Issue by JDDev0** [neoforged/NeoGradle#327]
NeoGradle: 7.1.38
NeoForge: 26.3.0.0-beta

EDIT: I fixed the patching problem, by deleting ~/.gradle in my home folder and the build and .gradle folders in my project.
Now I'm getting the weaker access problem with the HolderSet class during `neoFormRecompile` (Still only on NeoGradle it works with ModDevGradle):
```
<ProjectDir>/build/neoForm/neoFormJoined26.3-1/steps/transformSource/transformed/net/minecraft/core/HolderSet.java:44: error: contents() in <anonymous net.minecraft.core.HolderSet$1> cannot override contents() in Named
            protected List<Holder<T>> contents() {
                                      ^
  attempting to assign weaker access privileges; was public
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>emptyNamed(HolderOwner<T#1>,TagKey<T#1>)
    T#2 extends Object declared in class Named
```

PACTHING issue (fixed by clearing gradle caches):

Gradle sync output:
```
Starting Gradle Daemon...
Gradle Daemon started in 412 ms

> Configure project :
Disabling dist annotations on PMJ

> Task :neoFormListLibraries UP-TO-DATE
> Task :neoFormListTransformLibraries UP-TO-DATE
> Task :cacheVersionManifest26.3 UP-TO-DATE
> Task :cacheVersionExecutableClient26.3 UP-TO-DATE
> Task :cacheVersionExecutableServer26.3 UP-TO-DATE
> Task :neoFormSetup UP-TO-DATE
> Task :neoFormDecompile UP-TO-DATE
> Task :neoFormPatch UP-TO-DATE

> Task :neoFormPatchUserDev FAILED
[WARN] Patching: net/minecraft/world/level/block/Blocks.java
[WARN]  Hunk 0: FAILURE: @@ -802,7 +802,7 @@
[WARN]  Hunk 1: FAILURE: @@ -5936,7 +5936,8 @@
```

I have tested it with my own mod on 9.5.0.

I have also tested it with the Mod Generator (https://neoforged.net/mod-generator/) if `NeoGradle` is selected it cannot apply all patches.

With `ModDevGradle` all patches can be applied and the mod compiles.

Here is the patch from the rejects.zip:
```patch
++++ REJECTED HUNK: 1
@@ -802,7 +802,7 @@
             .pushReaction(PushReaction.POPPED)
     );
     public static final Block POWERED_RAIL = register(
-        BlockItemIds.POWERED_RAIL, PoweredRailBlock::new, BlockBehaviour.Properties.of().noCollision().strength(0.7F).sound(SoundType.METAL)
+        BlockItemIds.POWERED_RAIL, properties -> new PoweredRailBlock(properties, true), BlockBehaviour.Properties.of().noCollision().strength(0.7F).sound(SoundType.METAL)
     );
     public static final Block DETECTOR_RAIL = register(
         BlockItemIds.DETECTOR_RAIL, DetectorRailBlock::new, BlockBehaviour.Properties.of().noCollision().strength(0.7F).sound(SoundType.METAL)
++++ END HUNK

++++ REJECTED HUNK: 2
@@ -5936,7 +5936,8 @@
         SolidDebugger.runAndDump(() -> {
             for (Block block : BuiltInRegistries.BLOCK) {
                 for (BlockState state : block.getStateDefinition().getPossibleStates()) {
-                    Block.BLOCK_STATE_REGISTRY.add(state);
+                    // Neo: comment out, it's done in NeoForgeRegistryCallbacks
+                    //Block.BLOCK_STATE_REGISTRY.add(blockstate);
                     state.initCache();
                 }
             }
++++ END HUNK
```

**Comment by Herobrine011840** [comment]
I tried launching a small-ish workspace on 26.3.0.0 and got an issue with HolderSet, but it's pretty much the same issue

**Comment by KlemenDEV** [comment]
I can also confirm this happening

**Comment by iamkaf** [comment]
Also happens with ModDevGradle 2.0.141 and 2.0.147: `HolderSet$1.contents()` is generated as `protected`, but overrides the now-`public` `HolderSet.Named.contents()`.

**Comment by sciwhiz12** [comment]
> Also happens with ModDevGradle 2.0.141 and 2.0.147: `HolderSet$1.contents()` is generated as `protected`, but overrides the now-`public` `HolderSet.Named.contents()`.

This is the NeoGradle repository issue tracker. Please report issues regarding ModDevGradle to the appropriate issue tracker.

**Comment by JDDev0** [comment]
I fixed the patching problem, by deleting `~/.gradle` in my home folder and the `build` and `.gradle` folders in my project.

Now I'm getting the weaker access problem with the HolderSet class during `neoFormRecompile`:
```
<ProjectDir>/build/neoForm/neoFormJoined26.3-1/steps/transformSource/transformed/net/minecraft/core/HolderSet.java:44: error: contents() in <anonymous net.minecraft.core.HolderSet$1> cannot override contents() in Named
            protected List<Holder<T>> contents() {
                                      ^
  attempting to assign weaker access privileges; was public
  where T#1,T#2 are type-variables:
    T#1 extends Object declared in method <T#1>emptyNamed(HolderOwner<T#1>,TagKey<T#1>)
    T#2 extends Object declared in class Named
```

**Comment by sciwhiz12** [comment]
@Herobrine011840, your issue with the access modifier error in `HolderSet` is caused by NeoGradle using an older version of JavaSourceTransformer. I've pushed a commit https://github.com/neoforged/NeoGradle/commit/910f7d13ec81469496f3f33ae681bdccc8ec7a0d released as 7.1.39; please check if that fixes the issue for you.

@KlemenDEV, please clarify if your issue is the _exact_ patch application issue above, or if it's the same issue with the access modifier in `HolderSet`.

@JDDev0, please check if NG 7.1.39 fixes the issue for you.

---

In general, please only add on to an issue if it's the identical or nearly identical issue. As seen above, the patch issue as originally reported seems to be a caching issue, but the JavaSourceTransformer issue is different.

I'm going to consider this issue as tackling both, but please in the future don't crosspost unless it's actually identical.

**Comment by sciwhiz12** [comment]
Tested locally, and setting up an MDK for 26.3.0.0-beta works with NeoGradle **7.1.39**. Closing as resolved.

**Comment by KlemenDEV** [comment]
> @KlemenDEV, please clarify if your issue is the exact patch application issue above, or if it's the same issue with the access modifier in HolderSet.

It was the AT with holderset issue, but it fixed itself when I updated MDG, so it was likely outdated MDG I was using
